### ISSUE TITLE
Identify what's left to do on PRP demo infrastructure

### ISSUE THREAD

**Issue by rocketnova** [navapbc/wic-participant-recertification-portal-demo#8]
## Context

In July, we launched demonstration versions of the PRP as long-standing hosted examples of the work. There was a flurry of work at the end of the project based on #6, but #6 has still not been merged.

## Tasks

1. Verify that the current terraform state matches what is currently in #6 
  - In other words, there should be no manual overrides in the AWS Console for terraform-managed resources
  - Think about how you will demonstrate this
2. Identify if there are any resources deployed to AWS that are not captured in terraform
  - Did any manual changes happen the AWS Console that need to be transferred to terraform?
  - Think about how you will demonstrate this

Note: This ticket **does not** include doing any new terraform work. This ticket is specifically about performing research _before_ any terraform work begins.

**Comment by aplybeah** [comment]
@rocketnova here are my findings for the demo infrastructure:
1. The current terraform state matches what is in #6. This was verified by checking out the `alsia/manage-envs` branch and running a terraform plan
_screenshot after running terraform plan_
<img width="1064" alt="Screen Shot 2023-09-11 at 5 01 14 PM" src="https://github.com/navapbc/wic-participant-recertification-portal-demo/assets/37313082/55b56387-0ad9-473b-a672-a2c56a6a6da7">

2. I haven't seen any manual changes that needed to be added into terraform. Places looked:

- IAM
- S3
- SSM
- Databases
- Security Groups
- load balancers
- ECS
- ACM
3. There are a few things manually created that should probably be deleted.:

- `test-stage-staff-lambda` in security groups
- `wic-services.org` cert in ACM (us-east-1)

**Comment by rocketnova** [comment]
@aplybeah Thank you for doing this work! This looks excellent. I'll go ahead and merge PR #6 now.

**Comment by rocketnova** [comment]
Thank you for surfacing the additional manual components!

- I've manually deleted `test-stage-staff-lambda` in security groups. 
- I'm going to leave the `wic-services.org` cert in ACM (us-east-1) just in case we need it. Since it will auto-expire anyway, I think that's acceptable.
